runtime: python38

# Set App Engine instance class (defaults to F1)
# See https://cloud.google.com/appengine/docs/standard/#instance_classes
instance_class: F1

# Set entrypoint to locate Flask app, which is 'application' in module app/__init__.py
# Configure gunicorn worker count via --workers arg based on the App Engine instance class
# See https://cloud.google.com/appengine/docs/standard/python3/runtime#application_startup
entrypoint: gunicorn --workers 1 --worker-class gevent --bind :$PORT run:app

handlers:
- url: /favicon.ico
  static_files: application/static/img/favicon.ico
  upload: application/static/img/favicon.ico

- url: /robots.txt
  static_files: application/static/robots.txt
  upload: application/static/robots.txt

- url: /static
  static_dir: application/static
  secure: always

- url: /.*
  script: auto
  secure: always

includes:
  - env_production.yaml
